[core]
reloadable = true
order = 0

[package]
version = "1.0.1"
category = "Simulation"
title = "scripting.template.1"
description = "Scripting template"
authors = ["NVIDIA"]
repository = ""
keywords = []
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"


[dependencies]
"omni.kit.uiapp" = {}
"isaacsim.gui.components" = {}
"isaacsim.core.api" = {}

[[python.module]]
name = "scripting_template_1_python"